//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1624955_WebDevelopment.HomePage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImgID { get; set; }
        public string ImgName { get; set; }
        public Nullable<int> ImgWidth { get; set; }
        public Nullable<int> ImgHeight { get; set; }
        public string ImgExtension { get; set; }
        public string ImgAlternatetext { get; set; }
    }
}
